### ISSUE TITLE
[v0.17.0] Crashes on startup on Windows 10

### ISSUE THREAD

**Issue by zigzag312** [sc0ty/subsync#131]
I get this error on startup:

> C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
> Things are going to break, please only change locale by creating wxLocale objects to avoid this!
> 
> Traceback (most recent call last):
>   File "subsync\__main__.py", line 73, in gui
>   File "subsync\gui\mainwin.py", line 56, in __init__
>   File "subsync\gui\layout\mainwin.py", line 45, in __init__
>   File "subsync\gui\subpanel.py", line 63, in __init__
>   File "subsync\gui\subpanel.py", line 15, in __init__
>   File "subsync\gui\layout\subpanel.py", line 42, in __init__
> wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
> Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by GingerAdonis** [comment]
Sorry for the tag @sc0ty , but this is a major breaking bug. It would be appreciated if you can look into it. :)

**Comment by mimmiechan** [comment]
Same issue here.

**Comment by jiteshm17** [comment]
You can use an earlier version (0.16.0) from the releases page  [here](https://github.com/sc0ty/subsync/releases) and choosing the required installer based on the OS by under the Assets section. Just don't update the software till a fix has been released

**Comment by aka-charos** [comment]
same here (Win 21H2 OS Build 19044.1706)
