### ISSUE TITLE
[v0.17.0] Crashes on startup on Windows 11 Pro ver: 21H2 - 22000.348

### ISSUE THREAD

**Issue by vsantolo** [sc0ty/subsync#132]
I get this error on startup:

C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

Traceback (most recent call last):
  File "subsync\__main__.py", line 73, in gui
  File "subsync\gui\mainwin.py", line 56, in __init__
  File "subsync\gui\layout\mainwin.py", line 45, in __init__
  File "subsync\gui\subpanel.py", line 63, in __init__
  File "subsync\gui\subpanel.py", line 15, in __init__
  File "subsync\gui\layout\subpanel.py", line 42, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by dancer69** [comment]
I just installed subsync 0.17 in archlinux from aur. I comment here because one of the errors seems the same I had:
`File "subsync_main_.py", line 73, in gui`
I had some more info about this though and the problem was that the window size had unexpected type float. I solve it by change it to int. 
So maybe this help you too and also informs the developer about the issue(at least this one)

**Comment by githupper** [comment]
Same issue here in Windows 11 for 0.17.0.

0.16.0 works fine.

**Comment by m33ts4k0z** [comment]
Same for me.

**Comment by Slepetys** [comment]
Hi everyone,
This looks like it still needs to be solved.

After updating to Windows 11, I started having the same issue:

`C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

Traceback (most recent call last):
  File "subsync\__main__.py", line 73, in gui
  File "subsync\gui\mainwin.py", line 56, in __init__
  File "subsync\gui\layout\mainwin.py", line 45, in __init__
  File "subsync\gui\subpanel.py", line 63, in __init__
  File "subsync\gui\subpanel.py", line 15, in __init__
  File "subsync\gui\layout\subpanel.py", line 42, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!`

Did anyone have success fixing it?

This is really a nice software.

**Comment by ghostlyghastly** [comment]
FYI, 0.17 portable is hopeless
the MSI (extract via powertools or maybe lessmsi works too) has an apparently working subsync-cmd.exe (although I have other problems making it work)
