### ISSUE TITLE
Missing Norwegian - English

### ISSUE THREAD

**Issue by Timonsverden** [sc0ty/subsync#16]
Following assets are missing on server:

 - dictionary English / Norwegian

Traceback (most recent call last):
  File "D:\Michal\projects\subsync\subsync\gui\errorwin.py", line 75, in wrapper
  File "D:\Michal\projects\subsync\subsync\gui\batchwin.py", line 142, in onButtonStartClick
  File "D:\Michal\projects\subsync\subsync\gui\batchwin.py", line 146, in start
  File "D:\Michal\projects\subsync\subsync\gui\components\assetsdlg.py", line 44, in validateAssets
subsync.error.Error: Following assets are missing on server:

 - dictionary English / Norwegian

Any chance it will be avalible?

**Comment by sc0ty** [comment]
There will be new import from Wiktionary soon, I'm working on it right now, including English/Norwegian dictionary.

**Comment by Timonsverden** [comment]
now thank you. cant wait

**Comment by sc0ty** [comment]
done
