### ISSUE TITLE
Version 0.17 not working

### ISSUE THREAD

**Issue by eNdEmiOn** [sc0ty/subsync#168]
C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

Traceback (most recent call last):
  File "subsync\__main__.py", line 73, in gui
  File "subsync\gui\mainwin.py", line 56, in __init__
  File "subsync\gui\layout\mainwin.py", line 45, in __init__
  File "subsync\gui\subpanel.py", line 63, in __init__
  File "subsync\gui\subpanel.py", line 15, in __init__
  File "subsync\gui\layout\subpanel.py", line 42, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

This is the error message I get for both the portable and the install version. The previous version (0.16) is working just ok.

**Comment by MahiSt** [comment]
I'm getting this error as well

**Comment by pandit-tech** [comment]
I have this error too. i installed VC_redist.x64.exe and VC_redist.x86.exe
