### ISSUE TITLE
Missing dictionary Chinese / Portuguese

### ISSUE THREAD

**Issue by Pemicope** [sc0ty/subsync#19]
I keep getting this error:

Following assets are missing on server:

 - dictionary Chinese / Portuguese

Traceback (most recent call last):
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/errorwin.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/mainwin.py", line 146, in start
    if assetsdlg.validateAssets(self, [task], askForLang=askForLang):
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/components/assetsdlg.py", line 44, in validateAssets
    raise Error('\n'.join(msg))
subsync.error.Error: Following assets are missing on server:

 - dictionary Chinese / Portuguese

Is it possible to add it to SubSync? Thanks.

**Comment by sc0ty** [comment]
Added Chinese / Portuguese dictionary (based on Wiktionary)

**Comment by Pemicope** [comment]
Thank you! :smiley:
