### ISSUE TITLE
cli only version (docker)? pip3 failed.

### ISSUE THREAD

**Issue by BramFr** [sc0ty/subsync#22]
I`m trying to install subsync without gui. After ```pip3 install -r ./requirements.txt```

I`ll get the following message:
```
checking for GTK+ version...
    checking for pkg-config... no
    checking for GTK+ - version >= 3.0.0... no
    *** A new enough version of pkg-config was not found.
    *** See http://pkgconfig.sourceforge.net
    configure: error:
    The development files for GTK+ were not found. For GTK+ 2, please
    ensure that pkg-config is in the path and that gtk+-2.0.pc is
    installed. For GTK+ 1.2 please check that gtk-config is in the path,
    and that the version is 1.2.3 or above. Also check that the
    libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
    --libs' are in the LD_LIBRARY_PATH or equivalent.
    
    Error running configure
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "build.py", line 1325, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/tmp/pip-install-vyyimxo5/wxPython/buildtools/build_wxwidgets.py", line 373, in main
        "Error running configure")
      File "/tmp/pip-install-vyyimxo5/wxPython/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    buildtools.builder.BuildError: Error running configure
    Finished command: build_wx (0m10.827s)
    Finished command: build (0m10.827s)
    Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vyyimxo5/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cjs_m1s1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-vyyimxo5/wxPython/
```

is there any why to only use the cli methode ? Without snapd

**Comment by sc0ty** [comment]
Remove wxPython from requirements.txt

**Comment by BramFr** [comment]
Thanks, After gizmo build and subsync build and install i`ll still get this message:

```
root@657f751b68b1:/subsync# python3 ./subsync.py 
Traceback (most recent call last):
  File "./subsync.py", line 3, in <module>
    from subsync.__main__ import subsync
  File "/subsync/subsync/__main__.py", line 5, in <module>
    from subsync import translations
  File "/subsync/subsync/translations.py", line 4, in <module>
    from subsync import config
ImportError: cannot import name 'config' from 'subsync' (/subsync/subsync/__init__.py)
```

**Comment by sc0ty** [comment]
```
cd subsync/subsync
cp config.py.template config.py
```
I forgot to add it to the compilation guide. Or maybe setup.py should do it automatically.

**Comment by BramFr** [comment]
Thanks :) 

You didn't mentian to run "python setup.py install" within the gimzo folder.

```root@e5f5cf6bf2a1:/subsync# python3 ./subsync.py 
Traceback (most recent call last):
  File "./subsync.py", line 4, in <module>
    subsync()
  File "/subsync/subsync/__main__.py", line 16, in subsync
    initConfig(args)
  File "/subsync/subsync/__main__.py", line 43, in initConfig
    loggercfg.init(level=settings().logLevel, path=settings().logFile)
  File "/subsync/subsync/loggercfg.py", line 33, in init
    gizmo.setLoggerCallback(print_log)
AttributeError: module 'gizmo' has no attribute 'setLoggerCallback'
```

After the install command gimzo module works.

```
root@657f751b68b1:/subsync# python3 ./subsync.py 
09:27:19.216:  MainThread: WARNING:        subsync.__main__: couldn't start wx, falling back to headless mode, ModuleNotFoundError("No module named 'wx'")
09:27:19.852:  MainThread:   ERROR:        subsync.__main__: subsync failed, TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/subsync/subsync/__main__.py", line 90, in startCli
    app.runTasks()
  File "/subsync/subsync/cli.py", line 116, in runTasks
    for task in settings().tasks:
TypeError: 'NoneType' object is not iterable
```

i`ll think because i removed wxPython: **("No module named 'wx'")**

**Comment by sc0ty** [comment]
I will update compilation guide, sorry for that.
Are you building from head? It could be broken, try latest released version, tag 0.11.

**Comment by BramFr** [comment]
Thats works.

But what do you mean with sync,batch? 

```
root@3194353a9436:/subsync# python3 ./subsync.py -h
usage: subsync.py [-h] [--cli] [--verbose VERBOSE] [--window-size WINDOW_SIZE]
                  [--jobs JOBS] [--max-point-dist MAXPOINTDIST]
                  [--min-points-no MINPOINTSNO] [--min-word-prob MINWORDPROB]
                  [--min-word-len MINWORDLEN]
                  [--min-correlation MINCORRELATION]
                  [--min-words-sim MINWORDSSIM] [--loglevel LOGLEVEL]
                  [--logfile LOGFILE]
                  {sync,batch} ...

Subtitle Speech Synchronizer

positional arguments:
  {sync,batch}
    sync                synchronization
    batch               batch synchronization
```

do you have any example?

**Comment by sc0ty** [comment]
yep https://github.com/sc0ty/subsync/wiki/Command-line-options#batch-command

also try:
```
subsync.py sync -h
subsync.py batch -h
```

**Comment by sc0ty** [comment]
Updated installation instruction.

**Comment by BramFr** [comment]
Just for information:

https://hub.docker.com/r/bramfr/docker-subsync
