### ISSUE TITLE
Subsync won't open

### ISSUE THREAD

**Issue by Harp6** [sc0ty/subsync#23]
I just installed subsync with snap whem I try to open I get the following message:
```
/snap/subsync/6/bin/desktop-launch: line 295: [: too many arguments
translation language setup failed, FileNotFoundError(2, 'No translation file found for domain')
Traceback (most recent call last):
  File "/snap/subsync/6/bin/subsync", line 11, in <module>
    load_entry_point('subsync==0.11.0', 'gui_scripts', 'subsync')()
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/__main__.py", line 33, in subsync
    startGui(args)
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/__main__.py", line 52, in startGui
    from subsync.gui.mainwin import MainWin
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/mainwin.py", line 1, in <module>
    import subsync.gui.layout.mainwin
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/layout/mainwin.py", line 10, in <module>
    from subsync.gui.subpanel import SubPanel
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/gui/subpanel.py", line 4, in <module>
    from subsync.synchro import SubFile, RefFile
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/synchro/__init__.py", line 1, in <module>
    from subsync.synchro.synchronizer import Synchronizer
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/synchro/synchronizer.py", line 2, in <module>
    from subsync.synchro import pipeline
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/synchro/pipeline.py", line 2, in <module>
    from subsync.synchro import speech
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/synchro/speech.py", line 2, in <module>
    from subsync import assets
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/assets/__init__.py", line 1, in <module>
    from subsync.assets.mgr import AssetManager
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/assets/mgr.py", line 1, in <module>
    from subsync.assets import item
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/assets/item.py", line 1, in <module>
    from subsync.assets.updater import Updater
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/assets/updater.py", line 4, in <module>
    from subsync import async_utils
  File "/snap/subsync/6/lib/python3.5/site-packages/subsync/async_utils.py", line 2, in <module>
    import aiohttp
  File "/snap/subsync/6/lib/python3.5/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/snap/subsync/6/lib/python3.5/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/snap/subsync/6/lib/python3.5/site-packages/aiohttp/connector.py", line 20, in <module>
    from .client_proto import ResponseHandler
  File "/snap/subsync/6/lib/python3.5/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/snap/subsync/6/lib/python3.5/site-packages/aiohttp/http.py", line 1, in <module>
    import http.server
  File "/snap/subsync/6/usr/lib/python3.5/http/server.py", line 628, in <module>
    class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
  File "/snap/subsync/6/usr/lib/python3.5/http/server.py", line 836, in SimpleHTTPRequestHandler
    mimetypes.init() # try to read system mime.types
  File "/snap/subsync/6/usr/lib/python3.5/mimetypes.py", line 353, in init
    db.read(file)
  File "/snap/subsync/6/usr/lib/python3.5/mimetypes.py", line 202, in read
    with open(filename, encoding='utf-8') as fp:
PermissionError: [Errno 13] Permission denied: '/etc/httpd/conf/mime.types'
```

**Comment by sc0ty** [comment]
It looks like http module is trying to read /etc/httpd/conf/mime.types but has no rights to do so. Could you check the output of:
```
ls -l /etc/httpd/conf/mime.types
```
What system you are on? Is this released build of SubSync or you build it yourself?

**Comment by Harp6** [comment]
Here is the output:
-rw-rw-rw- 1 root root 60847 ago 13 19:44 /etc/httpd/conf/mime.types

I'm using manjaro, didn't build myself I installed with snap with the command: 
sudo snap install subsync

**Comment by sc0ty** [comment]
You found a bug in python package, or in snap system. It fails because http package tries to read this file, but it is restricted by the snap system. You got this file installed in your system probably by apache package.
Problem is I don't really know what to do about it. I couldn't find how to prevent http from trying to read this file.
You could try to run subsync in classic confinement, but you will give it full access to your file system - https://snapcraft.io/docs/snap-confinement

**Comment by sc0ty** [comment]
I've created a ticked in python bug tracker https://bugs.python.org/issue38672
Also managed to workaround this for subsync.
