### ISSUE TITLE
macOS build not working

### ISSUE THREAD

**Issue by sc0ty** [sc0ty/subsync#28]
Crashes with SSL error. Missing certifi package.
```
Traceback (most recent call last):
  File "aiohttp/connector.py", line 936, in _wrap_create_connection
  File "asyncio/base_events.py", line 970, in create_connection
  File "asyncio/base_events.py", line 998, in _create_connection_transport
  File "asyncio/sslproto.py", line 526, in data_received
  File "asyncio/sslproto.py", line 189, in feed_ssldata
  File "ssl.py", line 763, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "subsync/assets/listupdater.py", line 56, in downloadRemoteAssetList
  File "subsync/async_utils.py", line 38, in downloadJson
  File "aiohttp/client.py", line 1012, in __aenter__
  File "aiohttp/client.py", line 483, in _request
  File "aiohttp/connector.py", line 523, in connect
  File "aiohttp/connector.py", line 859, in _create_connection
  File "aiohttp/connector.py", line 1004, in _create_direct_connection
  File "aiohttp/connector.py", line 986, in _create_direct_connection
  File "aiohttp/connector.py", line 939, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "subsync/gui/errorwin.py", line 75, in wrapper
  File "subsync/gui/mainwin.py", line 154, in start
  File "subsync/gui/components/assetsdlg.py", line 35, in validateAssets
  File "subsync/gui/components/assetsdlg.py", line 63, in updateAssetList
  File "subsync/assets/listupdater.py", line 25, in hasList
subsync.error.Error: Communication with server failed
Cannot connect to host github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)’)]
```

When packaged again with certifi, there is an issue with pycryptodome:
```
Traceback (most recent call last):
  File “subsync/assets/updater.py”, line 71, in job
  File “subsync/assets/updater.py”, line 98, in download
  File “Crypto/Hash/SHA256.py”, line 158, in new
  File “Crypto/Hash/SHA256.py”, line 73, in __init__
  File “ctypes/__init__.py”, line 369, in __getattr__
  File “ctypes/__init__.py”, line 374, in __getitem__
AttributeError: dlsym(0x7f899ed73840, SHA256_init): symbol not found
```
Reported here https://github.com/pyinstaller/pyinstaller/issues/3993

**Comment by wesmosis** [comment]
Please fix.

**Comment by sc0ty** [comment]
It's already fixed, will be released this weekend, I think.

**Comment by wesmosis** [comment]
> It's already fixed, will be released this weekend, I think.

Thanks!

**Comment by starkblaze01** [comment]
Hi, Is the patch for this issue has already been released? Because I am still facing this error:
```
File "site-packages/Cryptodome/Cipher/PKCS1_OAEP.py", line 175, in decrypt
  File "site-packages/Cryptodome/Hash/SHA1.py", line 158, in new
  File "site-packages/Cryptodome/Hash/SHA1.py", line 74, in __init__
  File "ctypes/__init__.py", line 364, in __getattr__
  File "ctypes/__init__.py", line 369, in __getitem__
AttributeError: dlsym(0x7ffae9fcc090, SHA1_init): symbol not found
```
