### ISSUE TITLE
Improve encoding ISO-8859-1 Latin America

### ISSUE THREAD

**Issue by asyba** [sc0ty/subsync#76]
```Can't save subtitle file. 'latin-1' codec can't encode character '\u266a' in position 0: ordinal not in range(256)

Traceback (most recent call last):
  File "subsync\subtitle.py", line 49, in save
  File "lib\site-packages\pysubs2\ssafile.py", line 198, in save
  File "lib\site-packages\pysubs2\ssafile.py", line 230, in to_file
  File "lib\site-packages\pysubs2\subrip.py", line 97, in to_file
UnicodeEncodeError: 'latin-1' codec can't encode character '\u266a' in position 0: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "subsync\gui\errorwin.py", line 75, in wrapper
  File "subsync\gui\syncwin.py", line 204, in onButtonSaveClick
  File "subsync\gui\syncwin.py", line 208, in saveSynchronizedSubtitles
  File "subsync\subtitle.py", line 59, in save
subsync.error.Error: Can't save subtitle file. 'latin-1' codec can't encode character '\u266a' in position 0: ordinal not in range(256)
path:	J:\Series-B\Young Sheldon\Season 3\Young Sheldon - 3x20 - A Baby Tooth and the Egyptian God of Knowledge.spa.srt
encoding:	ISO-8859-1
```

**Comment by sc0ty** [comment]
You've got some characters that can't be converted to ISO-8859-1.
I'm not sure how this should be handled. I can see the following options:
1. Replace invalid characters with `�` or `?` and notify user about problems.
2. Ask user to select different encoding.
3. Show more legible error message.

I'm leaning towards first option since it requires no interaction with the user, which is important for headless mode. I'm not sure how it will work with pysubs2 (subtitles library), will have to investigate.

**Comment by asyba** [comment]
I think I found the issue.
I will close it for now.

**Comment by sc0ty** [comment]
Reopening since this still should be fixed.
Probably will take the approach from 1.

**Comment by sc0ty** [comment]
Now invalid characters will be replaced by `open(errors='replace', ...)`
