### ISSUE TITLE
Fatal error on invalid logFile path

### ISSUE THREAD

**Issue by ElimGarak72** [sc0ty/subsync#93]
Hello!
Today I've started running Subsync as usual and I got this error message:
![image](https://user-images.githubusercontent.com/67368032/87691334-66a53380-c782-11ea-92fe-7e4bf79a2d3e.png)

I've already tried to repair the installation, but the problem is still there. 

Thank you.

**Comment by sc0ty** [comment]
Could you try to [dump logs](https://github.com/sc0ty/subsync/wiki/How-to-dump-logs#from-command-line)? Also could you check what will `subsync-debug.exe` print on terminal?

**Comment by ElimGarak72** [comment]
Hello @sc0ty  and first of all thank you.

Unfortunately I can't. As soon as I press ENTER, I get the same error message.
![image](https://user-images.githubusercontent.com/67368032/87798434-e9da8e00-c843-11ea-8521-03317bc6c68d.png)

What I could do is run subsync-debug.exe and I got this:

D:\Programmi\Subsync>subsync-debug
[19220] PyInstaller Bootloader 3.x
[19220] LOADER: executable is D:\Programmi\Subsync\subsync-debug.exe
[19220] LOADER: homepath is D:\Programmi\Subsync
[19220] LOADER: _MEIPASS2 is NULL
[19220] LOADER: archivename is D:\Programmi\Subsync\subsync-debug.exe
[19220] LOADER: No need to extract files to run; setting extractionpath to homepath
[19220] LOADER: SetDllDirectory(D:\Programmi\Subsync)
[19220] LOADER: Already in the child - running user's code.
[19220] LOADER: Python library: D:\Programmi\Subsync\python36.dll
[19220] LOADER: Loaded functions from Python library.
[19220] LOADER: Manipulating environment (sys.path, sys.prefix)
[19220] LOADER: sys.prefix is D:\Programmi\Subsync
[19220] LOADER: Pre-init sys.path is D:\Programmi\Subsync\base_library.zip;D:\Programmi\Subsync
[19220] LOADER: Setting runtime options
[19220] LOADER: Initializing python
[19220] LOADER: Overriding Python's sys.path
[19220] LOADER: Post-init sys.path is D:\Programmi\Subsync\base_library.zip;D:\Programmi\Subsync
[19220] LOADER: Setting sys.argv
[19220] LOADER: setting sys._MEIPASS
[19220] LOADER: importing modules from CArchive
[19220] LOADER: extracted struct
[19220] LOADER: callfunction returned...
[19220] LOADER: extracted pyimod01_os_path
[19220] LOADER: callfunction returned...
[19220] LOADER: extracted pyimod02_archive
[19220] LOADER: callfunction returned...
[19220] LOADER: extracted pyimod03_importers
[19220] LOADER: callfunction returned...
[19220] LOADER: Installing PYZ archive with Python modules.
[19220] LOADER: PYZ archive: PYZ-00.pyz
[19220] LOADER: Running pyiboot01_bootstrap.py
[19220] LOADER: Running pyi_rth_multiprocessing.py
[19220] LOADER: Running subsync.py
Traceback (most recent call last):
  File "subsync", line 4, in <module>
  File "subsync\__main__.py", line 17, in subsync
  File "subsync\__main__.py", line 45, in initConfig
  File "subsync\loggercfg.py", line 40, in init
  File "logging\__init__.py", line 1808, in basicConfig
  File "logging\__init__.py", line 1032, in __init__
  File "logging\__init__.py", line 1061, in _open
FileNotFoundError: [Errno 2] No such file or directory: 'U:\\Incoming\\Serie TV\\Sex and the City\\Season 4\\log.txt'
[19220] Failed to execute script subsync
[19220] LOADER: OK.
[19220] LOADER: Cleaning up Python interpreter.

Thanks again!

**Comment by sc0ty** [comment]
You were supposed to change `/path/to/subsync.log` with path to log file.
Anyway I can see whats wrong from subsync-debug output. You have logs dumped to `U:\Incoming\Serie TV\Sex and the City\Season 4\log.txt` and this directory doesn't exist. Did you forgot to disable this and deleted this folder?

To recover from this you could either edit config file `%APPDATA%\subsync\subsync.json` (typically `C:\Users\<username>\subsync\subsync.json`) and remove `logFile` line, or delete this file entirely (you will lose your settings).

I will add some check to recover from similar situation with error that will not block startup.

**Comment by ElimGarak72** [comment]
It worked, thank you!

**Comment by sc0ty** [comment]
Will keep this open until I fix this.
